### ISSUE TITLE
How to develop locally/offline ?

### ISSUE THREAD

**Issue by zhangineer** [nautobot/nautobot-plugin-chatops-aci#12]
I have servers at home that can set up all of the components of nautobot, but I don't want to connect to slack over the internet just to develop features. Is there any guide on how to set up a local development environment? I am not very savvy with Slack chat. 

Or is it required that I set up a Nautobot server that's open to the internet for receiving commands from slack ?

**Comment by mamullen13316** [comment]
Hi @zhangineer,  I usually use ngrok (https://ngrok.com) for local development.  You would run that on your Nautobot server and it provides an Internet-reachable URL that you can configure as the target for Slack.

**Comment by zhangineer** [comment]
Thank you @mamullen13316 this is very helpful information !!
