### ISSUE TITLE
link to chat-setup-doc returns HTTP 404

### ISSUE THREAD

**Issue by cpaggen** [nautobot/nautobot-plugin-chatops-aci#14]
In the README.me for nautobot-plugin-chatops-aci, the [platform specific setup](https://github.com/nautobot/nautobot-plugin-chatops/blob/develop/docs/chat_setup/chat_setup.md#platform-specific-setup) link returns HTTP 404. I browsed the repo and there doesn't seem to be any doc for setting up the WebEx-side of things (or Slack, or other chat apps).

**Comment by smk4664** [comment]
Here is the new link, https://docs.nautobot.com/projects/chatops/en/latest/admin/install/#access-requirements.
